import { collection, doc, writeBatch } from "@react-native-firebase/firestore";
import { db } from "../../config/firebase";

const seedMenu = async () => {
	const restaurantId = "xD6c9KwlHJdY99gNFzTFhKdzVAH2";

	const menuItemsToSeed = [
		// ==========================================
		// COCKTAILS (DAIQUIRIS) - $9.00
		// ==========================================
		{
			name_en: "Pineapple Paradise Daiquiri",
			name_es: "Daiquiri Paraíso de Piña",
			description_en: "Fresh pineapple daiquiri made with Bacardi Silver Rum.",
			description_es: "Daiquiri fresco de piña hecho con ron Bacardi Silver.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Mango Madness Daiquiri",
			name_es: "Daiquiri Locura de Mango",
			description_en: "Fresh mango daiquiri made with Captain Morgan White.",
			description_es:
				"Daiquiri fresco de mango hecho con Captain Morgan White.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Coconut Breeze Daiquiri",
			name_es: "Daiquiri Brisa de Coco",
			description_en:
				"Refreshing coconut daiquiri made with Malibu Coconut Rum.",
			description_es:
				"Refrescante daiquiri de coco hecho con Malibu Coconut Rum.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Passion Fruit Storm Daiquiri",
			name_es: "Daiquiri Tormenta de Maracuyá",
			description_en: "Passion fruit daiquiri made with Flor de Cana 5 Year.",
			description_es: "Daiquiri de maracuyá hecho con Flor de Caña 5 Años.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Strawberry Splash Daiquiri",
			name_es: "Daiquiri Salpicón de Fresa",
			description_en: "Classic strawberry daiquiri made with Bacardi Superior.",
			description_es: "Daiquiri clásico de fresa hecho con Bacardi Superior.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Watermelon Wave Daiquiri",
			name_es: "Daiquiri Ola de Sandía",
			description_en: "Watermelon daiquiri made with Plantation 3 Star.",
			description_es: "Daiquiri de sandía hecho con Plantation 3 Star.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Blueberry Chill Daiquiri",
			name_es: "Daiquiri Escalofrío de Arándano",
			description_en: "Blueberry daiquiri made with Mount Gay Eclipse.",
			description_es: "Daiquiri de arándano hecho con Mount Gay Eclipse.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Banana Boat Daiquiri",
			name_es: "Daiquiri Barco de Plátano",
			description_en: "Banana daiquiri made with Havana Club Añejo Blanco.",
			description_es: "Daiquiri de plátano hecho con Havana Club Añejo Blanco.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Lemon Zest Delight Daiquiri",
			name_es: "Daiquiri Delicia de Limón",
			description_en: "Lemon daiquiri made with Tanqueray Gin.",
			description_es: "Daiquiri de limón hecho con ginebra Tanqueray.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Cucumber Mint Refresher",
			name_es: "Refrescante de Pepino y Menta",
			description_en: "Cucumber and mint daiquiri made with Gin.",
			description_es: "Daiquiri de pepino y menta hecho con ginebra.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Berry Basil Bliss Daiquiri",
			name_es: "Daiquiri Éxtasis de Moras y Albahaca",
			description_en: "Berry and basil daiquiri made with Beefeater Gin.",
			description_es:
				"Daiquiri de moras y albahaca hecho con ginebra Beefeater.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Tropical Lime Garden Daiquiri",
			name_es: "Daiquiri Jardín de Lima Tropical",
			description_en: "Tropical lime daiquiri made with Gordon's Gin.",
			description_es: "Daiquiri de lima tropical hecho con ginebra Gordon's.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Peach Bourbon Sunset",
			name_es: "Atardecer de Durazno y Bourbon",
			description_en: "Peach daiquiri made with Maker's Mark Bourbon.",
			description_es: "Daiquiri de durazno hecho con bourbon Maker's Mark.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Cherry Oak Smash",
			name_es: "Colisión de Cereza y Roble",
			description_en: "Cherry daiquiri made with Bulleit Bourbon.",
			description_es: "Daiquiri de cereza hecho con bourbon Bulleit.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Honey Citrus Kick",
			name_es: "Toque Cítrico con Miel",
			description_en: "Citrus and honey daiquiri made with Jim Beam Honey.",
			description_es: "Daiquiri de cítricos y miel hecho con Jim Beam Honey.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Spiced Apple Rush",
			name_es: "Frenesí de Manzana Especiada",
			description_en: "Spiced apple daiquiri made with Wild Turkey 101.",
			description_es:
				"Daiquiri de manzana especiada hecho con Wild Turkey 101.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Cinnamon Maple Twist",
			name_es: "Giro de Canela y Arce",
			description_en: "Cinnamon maple daiquiri made with Evan Williams.",
			description_es: "Daiquiri de canela y arce hecho con Evan Williams.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Vanilla Smoked Nectar",
			name_es: "Néctar Ahumado de Vainilla",
			description_en: "Vanilla daiquiri made with Knob Creek.",
			description_es: "Daiquiri de vainilla hecho con Knob Creek.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Coconut Barrel Chill",
			name_es: "Escalofrío de Barril de Coco",
			description_en: "Coconut bourbon daiquiri made with Four Roses.",
			description_es: "Daiquiri de bourbon y coco hecho con Four Roses.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Chocolate Mocha Storm",
			name_es: "Tormenta de Mocha y Chocolate",
			description_en: "Mocha chocolate daiquiri made with Buffalo Trace.",
			description_es: "Daiquiri de mocha y chocolate hecho con Buffalo Trace.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 900,
			restaurantId,
		},
		{
			name_en: "Daiquiri Flight (Any 5 Flavors)",
			name_es: "Vuelo de Daiquiris (5 Sabores)",
			description_en: "A tasting flight of any 5 daiquiri flavors.",
			description_es: "Una degustación de 5 sabores de daiquiri a elección.",
			category: "Cocktails",
			isDailySpecial: false,
			price: 2000,
			restaurantId,
		},

		// ==========================================
		// ENTREES (BURGERS & SANDWICHES)
		// ==========================================
		{
			name_en: "Deluxe Cheeseburger",
			name_es: "Hamburguesa de Lujo con Queso",
			description_en:
				"Classic deluxe cheeseburger with lettuce, tomato, and cheese.",
			description_es:
				"Clásica hamburguesa de lujo con queso, lechuga y tomate.",
			category: "Entrees",
			isDailySpecial: false,
			price: 1595,
			restaurantId,
		},
		{
			name_en: "Chicken Club / Bacon Sandwich",
			name_es: "Club de Pollo con Tocino",
			description_en: "Chicken club sandwich loaded with crispy bacon.",
			description_es: "Sándwich club de pollo con tocino crujiente.",
			category: "Entrees",
			isDailySpecial: false,
			price: 1395,
			restaurantId,
		},
		{
			name_en: "Spicy Chicken Sandwich",
			name_es: "Sándwich de Pollo Picante",
			description_en: "Crispy and spicy chicken sandwich.",
			description_es: "Sándwich de pollo crujiente y picante.",
			category: "Entrees",
			isDailySpecial: false,
			price: 1195,
			restaurantId,
		},
		{
			name_en: "Grilled Chicken Sandwich",
			name_es: "Sándwich de Pollo a la Parrilla",
			description_en: "Healthy and delicious grilled chicken sandwich.",
			description_es: "Saludable y delicioso sándwich de pollo a la parrilla.",
			category: "Entrees",
			isDailySpecial: false,
			price: 1195,
			restaurantId,
		},
		{
			name_en: "Fish Fillet Sandwich",
			name_es: "Sándwich de Pescado Crujiente",
			description_en: "Crispy fried fish fillet sandwich.",
			description_es: "Sándwich de filete de pescado frito y crujiente.",
			category: "Entrees",
			isDailySpecial: false,
			price: 1395,
			restaurantId,
		},
		{
			name_en: "BLT Sandwich",
			name_es: "Sándwich de Lechuga, Tomate y Tocino",
			description_en: "Classic Bacon, Lettuce, and Tomato sandwich.",
			description_es: "Sándwich clásico de tocino, lechuga y tomate.",
			category: "Entrees",
			isDailySpecial: false,
			price: 1395,
			restaurantId,
		},
		{
			name_en: "Chicken & Waffles",
			name_es: "Pollo con Waffles",
			description_en:
				"Crispy fried chicken served with a fluffy golden waffle.",
			description_es:
				"Pollo frito crujiente servido con un waffle dorado y esponjoso.",
			category: "Entrees",
			isDailySpecial: false,
			price: 1495,
			restaurantId,
		},
		{
			name_en: "Chicken Nuggets with Fries (8 Pieces)",
			name_es: "Nuggets de Pollo con Papas (8 Piezas)",
			description_en: "8 crispy chicken nuggets served with golden fries.",
			description_es:
				"8 nuggets de pollo crujientes servidos con papas fritas doradas.",
			category: "Entrees",
			isDailySpecial: false,
			price: 895,
			restaurantId,
		},
		{
			name_en: "Chicken Nuggets with Fries (12 Pieces)",
			name_es: "Nuggets de Pollo con Papas (12 Piezas)",
			description_en: "12 crispy chicken nuggets served with golden fries.",
			description_es:
				"12 nuggets de pollo crujientes servidos con papas fritas doradas.",
			category: "Entrees",
			isDailySpecial: false,
			price: 1295,
			restaurantId,
		},
		{
			name_en: "Chicken Strips with Fries (3 Pieces)",
			name_es: "Tiras de Pollo con Papas (3 Piezas)",
			description_en: "3 tender chicken strips served with fries.",
			description_es: "3 tiras de pollo tiernas servidas con papas fritas.",
			category: "Entrees",
			isDailySpecial: false,
			price: 795,
			restaurantId,
		},
		{
			name_en: "Chicken Strips with Fries (6 Pieces)",
			name_es: "Tiras de Pollo con Papas (6 Piezas)",
			description_en: "6 tender chicken strips served with fries.",
			description_es: "6 tiras de pollo tiernas servidas con papas fritas.",
			category: "Entrees",
			isDailySpecial: false,
			price: 995,
			restaurantId,
		},

		// ==========================================
		// APPETIZERS (NACHOS & SALADS)
		// ==========================================
		{
			name_en: "Nachos with Chicken or Beef",
			name_es: "Nachos con Pollo o Carne",
			description_en:
				"Crispy tortilla chips covered with beans, melted cheese, jalapenos, guacamole, sour cream, and tomatoes.",
			description_es:
				"Totopos crujientes con frijoles, queso derretido, jalapeños, guacamole, crema agria y tomates.",
			category: "Appetizers",
			isDailySpecial: false,
			price: 995,
			restaurantId,
		},
		{
			name_en: "Crisp Garden Salad",
			name_es: "Ensalada Fresca del Huerto",
			description_en: "Delicious crisp lettuce with chopped vegetables.",
			description_es: "Deliciosa y crujiente lechuga con vegetales picados.",
			category: "Appetizers",
			isDailySpecial: false,
			price: 995,
			restaurantId,
		},
		{
			name_en: "Garden Salad with Grilled Chicken & Bacon",
			name_es: "Ensalada con Pollo a la Parrilla y Tocino",
			description_en:
				"Crisp garden salad topped with grilled chicken and bacon.",
			description_es: "Ensalada fresca con pollo a la parrilla y tocino.",
			category: "Entrees",
			isDailySpecial: false,
			price: 1495,
			restaurantId,
		},
		{
			name_en: "Garden Salad with Crispy Chicken & Bacon",
			name_es: "Ensalada con Pollo Crujiente y Tocino",
			description_en: "Crisp garden salad topped with fried chicken and bacon.",
			description_es: "Ensalada fresca con pollo frito crujiente y tocino.",
			category: "Entrees",
			isDailySpecial: false,
			price: 1495,
			restaurantId,
		},

		// ==========================================
		// NON-ALCOHOLIC DRINKS
		// ==========================================
		{
			name_en: "Fresh Juice (16 oz)",
			name_es: "Jugo Fresco (16 oz)",
			description_en: "16 oz of refreshing fresh juice.",
			description_es: "16 oz de jugo fresco y refrescante.",
			category: "Non-Alcoholic Drinks",
			isDailySpecial: false,
			price: 500,
			restaurantId,
		},
		{
			name_en: "Lemonade",
			name_es: "Limonada",
			description_en: "Freshly squeezed lemonade.",
			description_es: "Limonada recién exprimida.",
			category: "Non-Alcoholic Drinks",
			isDailySpecial: false,
			price: 350,
			restaurantId,
		},
		{
			name_en: "Tropical Fruit Drink",
			name_es: "Bebida de Fruta Tropical",
			description_en: "Refreshing tropical fruit beverage.",
			description_es: "Refrescante bebida de frutas tropicales.",
			category: "Non-Alcoholic Drinks",
			isDailySpecial: false,
			price: 350,
			restaurantId,
		},
		{
			name_en: "Tamarind Drink",
			name_es: "Bebida de Tamarindo",
			description_en: "Sweet and tangy tamarind drink.",
			description_es: "Bebida dulce y ácida de tamarindo.",
			category: "Non-Alcoholic Drinks",
			isDailySpecial: false,
			price: 350,
			restaurantId,
		},
		{
			name_en: "Passion Fruit Drink",
			name_es: "Bebida de Maracuyá",
			description_en: "Sweet passion fruit beverage.",
			description_es: "Bebida dulce de maracuyá.",
			category: "Non-Alcoholic Drinks",
			isDailySpecial: false,
			price: 350,
			restaurantId,
		},
		{
			name_en: "Iced Tea",
			name_es: "Té Helado",
			description_en: "Classic chilled iced tea.",
			description_es: "Té helado clásico.",
			category: "Non-Alcoholic Drinks",
			isDailySpecial: false,
			price: 350,
			restaurantId,
		},
		{
			name_en: "Soda",
			name_es: "Refresco",
			description_en: "Assorted carbonated sodas.",
			description_es: "Refrescos carbonatados variados.",
			category: "Non-Alcoholic Drinks",
			isDailySpecial: false,
			price: 350,
			restaurantId,
		},
		{
			name_en: "Coffee / Hot Tea",
			name_es: "Café / Té Caliente",
			description_en: "Freshly brewed coffee or hot tea.",
			description_es: "Café recién hecho o té caliente.",
			category: "Non-Alcoholic Drinks",
			isDailySpecial: false,
			price: 350,
			restaurantId,
		},
		{
			name_en: "Bottled Water",
			name_es: "Agua Embotellada",
			description_en: "Purified bottled water.",
			description_es: "Agua purificada embotellada.",
			category: "Non-Alcoholic Drinks",
			isDailySpecial: false,
			price: 250,
			restaurantId,
		},

		// ==========================================
		// DESSERTS
		// ==========================================
		{
			name_en: "Classic Cheesecake",
			name_es: "Tarta de Queso Clásica",
			description_en: "Rich and creamy classic cheesecake.",
			description_es: "Tarta de queso clásica, rica y cremosa.",
			category: "Desserts",
			isDailySpecial: false,
			price: 895,
			restaurantId,
		},
		{
			name_en: "Caramel Cheesecake",
			name_es: "Tarta de Queso con Caramelo",
			description_en: "Cheesecake topped with rich caramel sauce.",
			description_es: "Tarta de queso cubierta con rica salsa de caramelo.",
			category: "Desserts",
			isDailySpecial: false,
			price: 1395,
			restaurantId,
		},
		{
			name_en: "Apple Cobbler",
			name_es: "Crujiente de Manzana",
			description_en: "Warm baked apple cobbler.",
			description_es: "Postre crujiente de manzana horneada caliente.",
			category: "Desserts",
			isDailySpecial: false,
			price: 895,
			restaurantId,
		},
		{
			name_en: "Tres Leches Cake",
			name_es: "Pastel de Tres Leches",
			description_en: "Traditional sponge cake soaked in three kinds of milk.",
			description_es: "Bizcocho tradicional bañado en tres tipos de leche.",
			category: "Desserts",
			isDailySpecial: false,
			price: 895,
			restaurantId,
		},
		{
			name_en: "Ice Cream Scoop",
			name_es: "Bola de Helado",
			description_en:
				"One scoop of Vanilla, Strawberry, or Chocolate ice cream.",
			description_es: "Una bola de helado de Vainilla, Fresa o Chocolate.",
			category: "Desserts",
			isDailySpecial: false,
			price: 395,
			restaurantId,
		},
		{
			name_en: "Ice Cream Trio",
			name_es: "Trío de Helados",
			description_en: "Three scoops of assorted ice cream.",
			description_es: "Tres bolas de helado surtido.",
			category: "Desserts",
			isDailySpecial: false,
			price: 895,
			restaurantId,
		},
		{
			name_en: "Dessert of the Week",
			name_es: "Postre de la Semana",
			description_en: "Ask your server about our special dessert of the week.",
			description_es:
				"Pregunte a su mesero por el postre especial de la semana.",
			category: "Desserts",
			isDailySpecial: false,
			price: 895,
			restaurantId,
		},
	];

	try {
		console.log("Starting batch upload for Daquiri 23...");
		const batch = writeBatch(db);

		menuItemsToSeed.forEach((item) => {
			const newItemRef = doc(collection(db, "menuItems"));
			batch.set(newItemRef, item);
		});

		await batch.commit();
		console.log("✅ Successfully seeded all menu items!");
	} catch (error) {
		console.error("❌ Error seeding menu items:", error);
	}
};

export default seedMenu;
